<?php

namespace App;

use App\Scopes\Reverse;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];


    public function user() {

        return $this->belongsTo(User::class);
    }

    public function likes() {

        return $this->belongsToMany(User::class,'likes','post_id','user_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new Reverse());
    }

    public function comments() {

        return $this->hasMany(Comment::class);
    }


}
